-- Crear base de datos dbCursos
CREATE DATABASE IF NOT EXISTS dbCurso
DEFAULT CHARACTER SET UTF8;

-- Poner en uso
USE dbCurso;

-- Crear tabla PERSONA
CREATE TABLE PERSONA
(
    DNIPER CHAR(8),
    NOMPER VARCHAR(50) NOT NULL,
    APEPER VARCHAR(80) NOT NULL,
    FECNACPER DATE,
    CELPER CHAR(9),
    EMAPER VARCHAR(100) NOT NULL,
    SEXPER CHAR(1),
    TIPPER CHAR(3),
    DISTPER VARCHAR(80) NOT NULL,
    FECREGPER TIMESTAMP,
    PWSPER VARCHAR(20) NOT NULL,
    CONSTRAINT DNIPER_PK PRIMARY KEY(DNIPER)
);

-- Crear tabla DEPARTAMENTO
CREATE TABLE DEPARTAMENTO
(
    IDDEP INT,
    NOMDEP VARCHAR(50) NOT NULL,
    DNIPER CHAR(8),
    SALJEFDEP DECIMAL(8.2),
    CONSTRAINT IDDEP_PK PRIMARY KEY(IDDEP)
);

-- Relacionar la tabla PERSONA - DEPARTAMENTO
ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PERSONA_DEPARTAMENTO_DNIPER
FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);